name: Add package tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        version: [0.0.1,0.0.100,0.0.200]
      fail-fast: false
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Add package
      run: dotnet add consume-test/consume-test.csproj package nuget-load -v ${{ matrix.version }}
